### ISSUE TITLE
Can't save latency monitor hosts list.

### ISSUE THREAD

**Issue by benjaminwanders** [Dragennd/NetworkAnalyzer#1]
In the latency monitor, on every start, I need to fill the (same) hosts again. Can we have it so that it can be saved?

**Comment by Dragennd** [comment]
I had not originally thought to add persisting targets to the Latency Monitor, but I like that idea. I'll see about implementing that in a future build.

**Comment by Dragennd** [comment]
@benjaminwanders Version 1.6.0 will introduce the Profile Manager. This will let you manage various monitoring profiles for both Latency Monitor modes which will persist between instances of the application.

https://github.com/Dragennd/NetworkAnalyzer/wiki/Feature-%E2%80%90-Latency-Monitor#profile-manager-available-v160

Update: [Version 1.6.0 is available today!](https://github.com/Dragennd/NetworkAnalyzer/releases/tag/1.6.0)
